// components/UserHoyo/puzzle/puzzlesData.ts

export interface Puzzle {
  id: number;
  title: string;
  game: 'hsr' | 'gi' | 'zzz' | 'hi3';
  difficulty: 'easy' | 'medium' | 'hard';
  type: 'riddle' | 'cipher' | 'lore-quiz' | 'sequence';
  question: string;
  options?: string[];
  answer: string;
  hint: string;
  lore: string;
  points: number;
  solvedBy: number;
  timeLimit?: number;
  orderIndex: number;
}

export const puzzlesData: Omit<Puzzle, 'id' | 'solvedBy'>[] = [
  // ==================== HONKAI: STAR RAIL (1-12) ====================
  {
    title: 'The Clockwork Paradox',
    game: 'hsr',
    difficulty: 'medium',
    type: 'riddle',
    question: 'I have hands but cannot clap. I speak but have no tongue. In Penacony I rule the night, yet vanish with the sun. What am I?',
    answer: 'clock',
    hint: 'Look at the architecture of the Grand Hotel.',
    lore: 'Clocks in Penacony are said to contain fragments of the Trailblaze Dream.',
    points: 150,
    timeLimit: 0,
    orderIndex: 1,
  },
  {
    title: 'The Shape of Reason',
    game: 'hsr',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'Which Path does Himeko walk, granting her mastery over the element of Fire?',
    options: ['The Hunt', 'Erudition', 'Destruction', 'Nihility'],
    answer: 'Erudition',
    hint: 'She was a scholar before becoming a crew member of the Astral Express.',
    lore: 'The Path of Erudition is associated with the Nous, the Aeon of intellect.',
    points: 80,
    timeLimit: 60,
    orderIndex: 2,
  },
  {
    title: 'Aeon\'s Riddle',
    game: 'hsr',
    difficulty: 'hard',
    type: 'riddle',
    question: 'I am the silence between stars, the void that dreams. Aeons fear my gaze, yet I am not malevolent. What am I?',
    options: ['IX - Nihility', 'Fuli - Remembrance', 'Terminus - Finality', 'HooH - Equilibrium'],
    answer: 'IX',
    hint: 'The Aeon who embodies the concept of nothingness itself.',
    lore: 'IX, the Aeon of Nihility, drifts through the cosmos as a living black hole.',
    points: 250,
    timeLimit: 90,
    orderIndex: 3,
  },
  {
    title: 'Xianzhou Alliance',
    game: 'hsr',
    difficulty: 'medium',
    type: 'lore-quiz',
    question: 'What is the name of the flagship of the Xianzhou Alliance?',
    options: ['The Luofu', 'The Yaoqing', 'The Fanghu', 'The Xuling'],
    answer: 'The Luofu',
    hint: 'It is the ship we visit during the main storyline.',
    lore: 'The Xianzhou Luofu is one of six ships in the Xianzhou Alliance.',
    points: 120,
    timeLimit: 45,
    orderIndex: 4,
  },
  {
    title: 'Stellaron Hunters',
    game: 'hsr',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'Which of these is NOT a member of the Stellaron Hunters?',
    options: ['Kafka', 'Silver Wolf', 'Blade', 'Jing Yuan'],
    answer: 'Jing Yuan',
    hint: 'The Stellaron Hunters are a group of outlaws.',
    lore: 'The Stellaron Hunters include Kafka, Silver Wolf, Blade, and Sam.',
    points: 70,
    timeLimit: 30,
    orderIndex: 5,
  },
  {
    title: 'Clockie\'s Secret',
    game: 'hsr',
    difficulty: 'hard',
    type: 'cipher',
    question: 'Decode: "FRZHV DUH IXQ" using Caesar cipher (shift +3).',
    options: ['CLOCKS ARE FUN', 'DREAMS ARE REAL', 'PUZZLES ARE HARD', 'TIME IS GOLD'],
    answer: 'CLOCKS ARE FUN',
    hint: 'Each letter shifts backward by 3 positions.',
    lore: 'Clockie hides secret messages throughout the Dreamscape.',
    points: 200,
    timeLimit: 60,
    orderIndex: 6,
  },
  {
    title: 'Path of Trailblaze',
    game: 'hsr',
    difficulty: 'medium',
    type: 'sequence',
    question: 'Complete: Astral Express → ??? → Herta Station → Penacony',
    options: ['Belobog', 'Xianzhou Luofu', 'Jarilo-VI', 'The Shackling Prison'],
    answer: 'Jarilo-VI',
    hint: 'The first major stop after the Herta Space Station.',
    lore: 'Jarilo-VI was the Trailblazer\'s first real adventure.',
    points: 130,
    timeLimit: 40,
    orderIndex: 7,
  },
  {
    title: 'Divine Foresight',
    game: 'hsr',
    difficulty: 'hard',
    type: 'lore-quiz',
    question: 'Who is the Master Diviner of the Xianzhou Luofu?',
    options: ['Fu Xuan', 'Qingque', 'Fu Hua', 'Bailu'],
    answer: 'Fu Xuan',
    hint: 'She uses the Matrix of Prescience to predict the future.',
    lore: 'Fu Xuan uses her third eye to calculate probabilities.',
    points: 180,
    timeLimit: 50,
    orderIndex: 8,
  },
  {
    title: 'Belobog History',
    game: 'hsr',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'What is the name of the Supreme Guardian of Belobog?',
    options: ['Cocolia', 'Bronya', 'Seele', 'Serval'],
    answer: 'Cocolia',
    hint: 'She was the mother of Bronya.',
    lore: 'Cocolia was the Supreme Guardian before her betrayal.',
    points: 75,
    timeLimit: 30,
    orderIndex: 9,
  },
  {
    title: 'The Silver Rail',
    game: 'hsr',
    difficulty: 'medium',
    type: 'lore-quiz',
    question: 'Who is the conductor of the Astral Express?',
    options: ['Pom-Pom', 'Himeko', 'Welt', 'March 7th'],
    answer: 'Pom-Pom',
    hint: 'A small, furry creature in a conductor\'s hat.',
    lore: 'Pom-Pom has been the conductor for as long as anyone can remember.',
    points: 100,
    timeLimit: 25,
    orderIndex: 10,
  },
  {
    title: 'Luocha\'s Secret',
    game: 'hsr',
    difficulty: 'hard',
    type: 'riddle',
    question: 'I carry a coffin wherever I go. I heal the wounded but cannot heal myself. Who am I?',
    answer: 'luocha',
    hint: 'A traveling merchant from beyond the Xianzhou.',
    lore: 'Luocha\'s coffin contains a secret he never reveals.',
    points: 220,
    timeLimit: 0,
    orderIndex: 11,
  },
  {
    title: 'Jingliu\'s Curse',
    game: 'hsr',
    difficulty: 'hard',
    type: 'lore-quiz',
    question: 'What affliction does Jingliu suffer from?',
    options: ['Mara', 'Stellaron corruption', 'Emanator status', 'Memory loss'],
    answer: 'Mara',
    hint: 'A curse that affects long-lived species.',
    lore: 'Jingliu succumbed to Mara after centuries of battle.',
    points: 200,
    timeLimit: 45,
    orderIndex: 12,
  },

  // ==================== GENSHIN IMPACT (13-24) ====================
  {
    title: 'Seven Nations Cipher',
    game: 'gi',
    difficulty: 'hard',
    type: 'cipher',
    question: 'Decode: MNQSDI → LIYUE. Using same shift, decode: XTKX',
    options: ['WAVE', 'WIND', 'VEIL', 'VALE'],
    answer: 'WIND',
    hint: 'M→L is -1 shift.',
    lore: 'The Seven Archons sealed secrets in cipher texts.',
    points: 300,
    timeLimit: 90,
    orderIndex: 13,
  },
  {
    title: 'Dandelion Riddle',
    game: 'gi',
    difficulty: 'medium',
    type: 'riddle',
    question: 'I bloom without soil, I carry hopes to the sky. Mondstadt calls me sacred. What am I?',
    answer: 'dandelion seed',
    hint: 'Jean uses me in her healing arts.',
    lore: 'Dandelion Seeds represent freedom and wishes.',
    points: 150,
    timeLimit: 0,
    orderIndex: 14,
  },
  {
    title: 'Archon War History',
    game: 'gi',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'Which Archon was the victor in Liyue?',
    options: ['Barbatos', 'Morax', 'Baal', 'Buer'],
    answer: 'Morax',
    hint: 'Also known as the God of Contracts.',
    lore: 'Rex Lapis founded Liyue over 6,000 years ago.',
    points: 80,
    timeLimit: 30,
    orderIndex: 15,
  },
  {
    title: 'Abyss Order',
    game: 'gi',
    difficulty: 'medium',
    type: 'lore-quiz',
    question: 'Who founded the Abyss Order?',
    options: ['Dainsleif', 'The Traveler\'s Sibling', 'Gold', 'King Irmin'],
    answer: 'The Traveler\'s Sibling',
    hint: 'Once the Prince/Princess of Khaenri\'ah.',
    lore: 'The sibling became leader after Khaenri\'ah\'s fall.',
    points: 160,
    timeLimit: 45,
    orderIndex: 16,
  },
  {
    title: 'Elemental Reaction',
    game: 'gi',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'Hydro + Electro = ?',
    options: ['Vaporize', 'Electro-Charged', 'Overloaded', 'Superconduct'],
    answer: 'Electro-Charged',
    hint: 'Continuous Electro damage.',
    lore: 'Electro-Charged stuns enemies in water.',
    points: 70,
    timeLimit: 20,
    orderIndex: 17,
  },
  {
    title: 'Harbinger Secrets',
    game: 'gi',
    difficulty: 'hard',
    type: 'sequence',
    question: 'Fatui Harbingers: Pierro(0), Dottore(??), Columbina(??), Capitano(??)',
    options: ['2,3,4', '1,2,3', '3,4,5', '2,4,6'],
    answer: '2,3,4',
    hint: 'Numbered 1-11, Pierro is Director (0).',
    lore: 'Dottore #2, Columbina #3, Capitano #4.',
    points: 220,
    timeLimit: 60,
    orderIndex: 18,
  },
  {
    title: 'Celestia Mystery',
    game: 'gi',
    difficulty: 'hard',
    type: 'riddle',
    question: 'I float above, watching all. Seven thrones sit beneath my shadow. What am I?',
    answer: 'celestia',
    hint: 'Visible from certain points in Teyvat.',
    lore: 'Celestia is the dwelling place of the gods.',
    points: 280,
    timeLimit: 0,
    orderIndex: 19,
  },
  {
    title: 'Vision Types',
    game: 'gi',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'How many Vision types exist?',
    options: ['5', '6', '7', '8'],
    answer: '7',
    hint: 'One for each element.',
    lore: 'Pyro, Hydro, Anemo, Electro, Dendro, Cryo, Geo.',
    points: 60,
    timeLimit: 20,
    orderIndex: 20,
  },
  {
    title: 'The Seven Archons',
    game: 'gi',
    difficulty: 'medium',
    type: 'lore-quiz',
    question: 'Which Archon is the God of Wisdom?',
    options: ['Nahida', 'Venti', 'Zhongli', 'Raiden'],
    answer: 'Nahida',
    hint: 'She is the Dendro Archon of Sumeru.',
    lore: 'Nahida is the youngest of the Seven Archons.',
    points: 110,
    timeLimit: 35,
    orderIndex: 21,
  },
  {
    title: 'Khaenri\'ah',
    game: 'gi',
    difficulty: 'hard',
    type: 'lore-quiz',
    question: 'What cataclysm destroyed Khaenri\'ah?',
    options: ['The Abyss', 'The Cataclysm', 'The Archon War', 'The Heavenly Principles'],
    answer: 'The Cataclysm',
    hint: 'Occurred 500 years ago.',
    lore: 'The Cataclysm involved the Abyss and the Seven Archons.',
    points: 250,
    timeLimit: 50,
    orderIndex: 22,
  },
  {
    title: 'Dainsleif\'s Mission',
    game: 'gi',
    difficulty: 'medium',
    type: 'lore-quiz',
    question: 'What is Dainsleif searching for?',
    options: ['The Loom of Fate', 'The Field Tiller', 'The Abyss Twin', 'The Holy Lyre'],
    answer: 'The Loom of Fate',
    hint: 'An artifact that can weave destiny.',
    lore: 'The Loom of Fate is key to the Abyss Order\'s plans.',
    points: 140,
    timeLimit: 40,
    orderIndex: 23,
  },
  {
    title: 'The Tsaritsa',
    game: 'gi',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'What is the Tsaritsa\'s element?',
    options: ['Cryo', 'Pyro', 'Hydro', 'Electro'],
    answer: 'Cryo',
    hint: 'She is the Cryo Archon of Snezhnaya.',
    lore: 'The Tsaritsa has no love left for her people.',
    points: 65,
    timeLimit: 20,
    orderIndex: 24,
  },

  // ==================== ZENLESS ZONE ZERO (25-34) ====================
  {
    title: 'Hollow Frequency',
    game: 'zzz',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'What system does Phaethon use for missions?',
    options: ['HolloCast', 'InterKnot', 'NetSphere', 'DataWave'],
    answer: 'InterKnot',
    hint: 'Also where Bangboo memes go viral.',
    lore: 'InterKnot is New Eridu\'s digital backbone.',
    points: 80,
    timeLimit: 30,
    orderIndex: 25,
  },
  {
    title: 'Agent Code Cipher',
    game: 'zzz',
    difficulty: 'medium',
    type: 'cipher',
    question: 'Nicole=N-1, Billy=B-2, Corin=C-3. What is Soldier 11?',
    options: ['S-11', 'S-01', 'S-2', 'Uses title'],
    answer: 'S-11',
    hint: 'First letter + number in name.',
    lore: 'Agents conceal identities with codenames.',
    points: 180,
    timeLimit: 45,
    orderIndex: 26,
  },
  {
    title: 'Belobog Industries',
    game: 'zzz',
    difficulty: 'medium',
    type: 'lore-quiz',
    question: 'Who is president of Belobog Industries?',
    options: ['Koleda Belobog', 'Grace Howard', 'Anton Ivanov', 'Ben Bigger'],
    answer: 'Koleda Belobog',
    hint: 'Inherited from her father.',
    lore: 'Koleda leads the construction giant.',
    points: 140,
    timeLimit: 35,
    orderIndex: 27,
  },
  {
    title: 'Hollow Zero',
    game: 'zzz',
    difficulty: 'hard',
    type: 'riddle',
    question: 'I am the source of all Hollows, the original corruption. What am I?',
    options: ['The Creator', 'The Hollow Heart', 'The Nineveh', 'The Eridu Core'],
    answer: 'The Hollow Heart',
    hint: 'Origin point beneath New Eridu.',
    lore: 'Understanding it is key to saving humanity.',
    points: 250,
    timeLimit: 0,
    orderIndex: 28,
  },
  {
    title: 'Bangboo Types',
    game: 'zzz',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'Which Bangboo is for combat and healing?',
    options: ['Amillion', 'Butler', 'Explorer', 'Officer Cui'],
    answer: 'Butler',
    hint: 'Wears a bow tie and carries a tray.',
    lore: 'Butler Bangboos provide healing and buffs.',
    points: 70,
    timeLimit: 25,
    orderIndex: 29,
  },
  {
    title: 'Proxy Identity',
    game: 'zzz',
    difficulty: 'hard',
    type: 'lore-quiz',
    question: 'Who is the Proxy "Phaethon"?',
    options: ['Wise and Belle', 'Cunning Hares', 'Section 6', 'The Vision'],
    answer: 'Wise and Belle',
    hint: 'Siblings operating from Random Play.',
    lore: 'Wise and Belle are legendary Proxies.',
    points: 200,
    timeLimit: 50,
    orderIndex: 30,
  },
  {
    title: 'Section 6',
    game: 'zzz',
    difficulty: 'medium',
    type: 'sequence',
    question: 'Order Section 6 by rank: ??? → ??? → ??? → Souichiro',
    options: ['Asaba→Tsukishiro→Yanagi', 'Hoshimi→Tsukishiro→Asaba', 'Yanagi→Asaba→Tsukishiro', 'Tsukishiro→Yanagi→Asaba'],
    answer: 'Asaba→Tsukishiro→Yanagi',
    hint: 'Asaba leader, Tsukishiro second, Yanagi third.',
    lore: 'Section 6 is the elite Hollow investigation team.',
    points: 160,
    timeLimit: 40,
    orderIndex: 31,
  },
  {
    title: 'The Cunning Hares',
    game: 'zzz',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'Who leads the Cunning Hares?',
    options: ['Nicole', 'Billy', 'Anby', 'Nekomata'],
    answer: 'Nicole',
    hint: 'The pink-haired debt collector.',
    lore: 'Nicole runs the faction with charisma.',
    points: 75,
    timeLimit: 25,
    orderIndex: 32,
  },
  {
    title: 'Victoria Housekeeping',
    game: 'zzz',
    difficulty: 'medium',
    type: 'lore-quiz',
    question: 'Who is the butler of Victoria Housekeeping?',
    options: ['Lycaon', 'Rina', 'Corin', 'Ellen'],
    answer: 'Lycaon',
    hint: 'A wolf-like thiren in formal attire.',
    lore: 'Lycaon serves as the head butler.',
    points: 130,
    timeLimit: 35,
    orderIndex: 33,
  },
  {
    title: 'The Vision',
    game: 'zzz',
    difficulty: 'hard',
    type: 'lore-quiz',
    question: 'What is The Vision\'s goal?',
    options: ['Control Hollows', 'Destroy Eridu', 'Save New Eridu', 'Find the Creator'],
    answer: 'Control Hollows',
    hint: 'They seek power over the Hollows.',
    lore: 'The Vision is a mysterious antagonist faction.',
    points: 190,
    timeLimit: 45,
    orderIndex: 34,
  },

  // ==================== HONKAI IMPACT 3RD (35-44) ====================
  {
    title: 'Honkai Sequence',
    game: 'hi3',
    difficulty: 'hard',
    type: 'sequence',
    question: 'Mauvewolf → Jotun → ??? → Herrscher of Corruption',
    options: ['Nexus', 'Benares', 'Parvati', 'Vishnu'],
    answer: 'Benares',
    hint: 'The Crimson Dragon.',
    lore: 'Benares accompanied Fu Hua across centuries.',
    points: 320,
    timeLimit: 60,
    orderIndex: 35,
  },
  {
    title: 'The Thirteen Moons',
    game: 'hi3',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'What organization does Bronya lead?',
    options: ['Anti-Entropy', 'Schicksal', 'World Serpent', 'Azure Waters'],
    answer: 'Anti-Entropy',
    hint: 'Founded by Einstein and Tesla.',
    lore: 'Bronya became Supreme Commander of Anti-Entropy.',
    points: 80,
    timeLimit: 30,
    orderIndex: 36,
  },
  {
    title: 'Flame-Chasers',
    game: 'hi3',
    difficulty: 'hard',
    type: 'lore-quiz',
    question: 'How many Flame-Chasers were there?',
    options: ['7', '11', '13', '15'],
    answer: '13',
    hint: 'Named after Chinese zodiac signs.',
    lore: 'The Thirteen Flame-Chasers fought the Honkai.',
    points: 220,
    timeLimit: 45,
    orderIndex: 37,
  },
  {
    title: 'Herrscher Riddle',
    game: 'hi3',
    difficulty: 'medium',
    type: 'riddle',
    question: 'I am Herrscher of Thunder, but rejected my nature. Daughter of a dragon, yet fight for humanity. Who am I?',
    answer: 'mei',
    hint: 'From Nagazora City, attends St. Freya.',
    lore: 'Raiden Mei chose to protect humanity.',
    points: 150,
    timeLimit: 0,
    orderIndex: 38,
  },
  {
    title: 'St. Freya',
    game: 'hi3',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'Where did Kiana, Mei, and Bronya study?',
    options: ['St. Freya Academy', 'Schicksal HQ', 'Theater of Domination', 'Hyperion'],
    answer: 'St. Freya Academy',
    hint: 'Island in the Pacific.',
    lore: 'Founded by Theresa Apocalypse.',
    points: 70,
    timeLimit: 25,
    orderIndex: 39,
  },
  {
    title: 'World Serpent',
    game: 'hi3',
    difficulty: 'hard',
    type: 'lore-quiz',
    question: 'Who leads World Serpent?',
    options: ['Kevin Kaslana', 'Gray Serpent', 'Jackal', 'Raven'],
    answer: 'Kevin Kaslana',
    hint: 'Survivor from Previous Era.',
    lore: 'Kevin seeks to save humanity through Project STIGMA.',
    points: 240,
    timeLimit: 50,
    orderIndex: 40,
  },
  {
    title: 'Elysian Realm',
    game: 'hi3',
    difficulty: 'medium',
    type: 'lore-quiz',
    question: 'What is the Elysian Realm?',
    options: ['Simulation of Previous Era', 'Bubble universe', 'Honkai zone', 'Schicksal lab'],
    answer: 'Simulation of Previous Era',
    hint: 'Contains memories of Flame-Chasers.',
    lore: 'Created by Mobius to preserve memories.',
    points: 170,
    timeLimit: 40,
    orderIndex: 41,
  },
  {
    title: 'Kiana\'s Journey',
    game: 'hi3',
    difficulty: 'easy',
    type: 'lore-quiz',
    question: 'What is Kiana\'s real name?',
    options: ['Kiana Kaslana', 'K-423', 'Sirin', 'The Herrscher of Void'],
    answer: 'K-423',
    hint: 'She is a clone created by Otto.',
    lore: 'K-423 was created from Sirin\'s DNA.',
    points: 85,
    timeLimit: 30,
    orderIndex: 42,
  },
  {
    title: 'Durandal',
    game: 'hi3',
    difficulty: 'medium',
    type: 'lore-quiz',
    question: 'What is Durandal\'s real name?',
    options: ['Bianka Ataegina', 'Rita Rossweisse', 'Theresa Apocalypse', 'Seele Vollerei'],
    answer: 'Bianka Ataegina',
    hint: 'The strongest Valkyrie of Schicksal.',
    lore: 'Durandal is captain of Squad Immortal Blades.',
    points: 135,
    timeLimit: 35,
    orderIndex: 43,
  },
  {
    title: 'Seele Vollerei',
    game: 'hi3',
    difficulty: 'medium',
    type: 'lore-quiz',
    question: 'What is the name of Seele\'s dark personality?',
    options: ['Dark Seele', 'Seele\'s Shadow', 'Veliona', 'The Herrscher of Death'],
    answer: 'Veliona',
    hint: 'Protects Seele from danger.',
    lore: 'Veliona is Seele\'s alter ego and protector.',
    points: 125,
    timeLimit: 35,
    orderIndex: 44,
  },
];